
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .html
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    check-template-location: true

system:
  version: 0

shiro:
  sql:
    roles: select distinct r.code from tbl_user_role ur left join tbl_role r on ur.roleId=r.id left join tbl_user u on ur.userId=u.id where u.login_name=:param
page:
    main: redirect:/
    login: login
    register: register
server:
  port: 80
  context-path: /


