server:
  port: 80
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .html
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    check-template-location: true
  jpa:
    hibernate:
      ddl-auto: update
      #解决Spring Data JPA @Column 注解无效
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


system:
  version: 0
page:
    main: redirect:/
    login: login
    register: register



