spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    check-template-location: true
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java
  profiles:
    active: dev
server:
  session:
    timeout: 1000
  tomcat:
    uri-encoding: UTF-8
  context-path: /
system:
  needPassword: 1
  mainPage: redirect:/
  loginPage: pages/login
  registerPage: register


