server:
  port: 80
spring:
  datasource:
    #WARN: Establishing SSL connection without server's identity verification is not recommended ：加useSSL=true消除警告
    url: jdbc:mysql://192.168.0.103:3306/springbootdb?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cluster:
      nodes:
              - 192.168.0.99:6380
              - 192.168.0.99:6381
              - 192.168.0.99:6382
              - 192.168.0.98:6380
              - 192.168.0.98:6381
              - 192.168.0.98:6382
mybatis:
  type-aliases-package: domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30