spring:
  datasource:
    url: jdbc:mysql://192.168.0.120:3306/springbootdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    check-template-location: true
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8
  devtools:
    livereload:
      enabled: true
server:
  port: 80
  session:
    timeout: 1000
  tomcat:
    uri-encoding: UTF-8

system:
  needPassword: 1
  mainPage: redirect:/
  loginPage: pages/login
  registerPage: register



