server:
  port: 80
spring:
  datasource:
    #WARN: Establishing SSL connection without server's identity verification is not recommended ：加useSSL=true消除警告
    url: jdbc:mysql://192.168.0.119:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#  redis:
#    cluster:
#      nodes:
#              - 192.168.0.99:6380
#              - 192.168.0.99:6381
#              - 192.168.0.99:6382
#              - 192.168.0.98:6380
#              - 192.168.0.98:6381
#              - 192.168.0.98:6382
#mybatis:
#  type-aliases-package: domain
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#      map-underscore-to-camel-case: true
#      default-fetch-size: 100
#      default-statement-timeout: 30